### ISSUE TITLE
Duplicated modules: 'Elixir.Poison.Encoder.Ecto.Association.NotLoaded' 

### ISSUE THREAD

**Issue by whitered** [kagux/ex_debug_toolbar#66]
When I run `mix edeliver build release production` on a project with ecto 2.2.6 and ex_debug_toolbar 0.4.0 in deps:
```
==> Release failed, during .boot generation:
        Duplicated modules:
    	'Elixir.Poison.Encoder.Ecto.Association.NotLoaded' specified in ecto and ex_debug_toolbar
```

**Comment by whitered** [comment]
Here are the compilation logs:
```
$ mix deps.compile ex_debug_toolbar --force
==> ex_debug_toolbar
Compiling 52 files (.ex)
warning: redefining module Mix.Tasks.Compile.ExDebugToolbar (current version defined in memory)
  lib/mix/tasks/compile.ex_debug_toolbar.ex:1

warning: redefining module Poison.Encoder.Ecto.Association.NotLoaded (current version loaded from /Users/me/app/_build/dev/lib/ecto/ebin/Elixir.Poison.Encoder.Ecto.Association.NotLoaded.beam)
  lib/ex_debug_toolbar/poison/encoder.ex:17

warning: redefining module ExDebugToolbar.Application (current version defined in memory)
  lib/ex_debug_toolbar/application.ex:1

warning: function PhoenixSlime.Engine.compile/2 is undefined (module PhoenixSlime.Engine is not available)
  lib/ex_debug_toolbar/template/slim_engine.ex:4

Generated ex_debug_toolbar app
```

**Comment by kagux** [comment]
hey @whitered,  I've published update 0.4.1 that should remove these warning. Can you give it a try?

**Comment by whitered** [comment]
Not yet, edeliver build fails with the same message. Compiler output has changed though:
```
$ mix deps.compile ex_debug_toolbar --force
==> ex_debug_toolbar
Compiling 52 files (.ex)
warning: redefining module Mix.Tasks.Compile.ExDebugToolbar (current version defined in memory)
  lib/mix/tasks/compile.ex_debug_toolbar.ex:1

Generated ex_debug_toolbar app
```

**Comment by kagux** [comment]
pushed 0.4.2 to fix this last warning

**Comment by whitered** [comment]
Compiler warnings gone away, but edeliver still fails to build release on remote server
```
==> Release failed, during .boot generation:
        Duplicated modules:
    	'Elixir.Poison.Encoder.Ecto.Association.NotLoaded' specified in ecto and ex_debug_toolbar
```

**Comment by kagux** [comment]
Just to make sure, does remote server have latest package?

**Comment by whitered** [comment]
Yes, it's 0.4.2 on my build server

**Comment by kagux** [comment]
alright, I'll have to reproduce it using edeliver in that case. Let me see what I can do tomorrow.

**Comment by kagux** [comment]
With latest changes in 0.4.3 it worked for me with `edelivery` and `distillery`

**Comment by whitered** [comment]
It works for me too now, thank you very much!
